# Aider Configuration for n8n Custom Node Development
# See: https://aider.chat/docs/config/aider_conf.html

# Read project rules from AGENTS.md
read:
  - AGENTS.md
  - docs/10-creating-your-first-node.md
  - docs/12-declarative-routing.md
  - docs/13-custom-execute-methods.md

# Lint command for code quality
lint-cmd: npm run lint

# Auto-apply lint fixes
auto-lint: true

# Git settings
auto-commits: true
dirty-commits: false

# Model settings (customize as needed)
# model: claude-3-5-sonnet-20241022

# File patterns to watch
watch-files:
  - "nodes/**/*.ts"
  - "credentials/**/*.ts"

# Ignore patterns
ignore-files:
  - "dist/**"
  - "node_modules/**"
  - "*.tsbuildinfo"
